---
services:
  nats:
    build:
      context: ./nats
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data/nats

volumes:
  nats_data: {}
