---
services:
  nats:
    build:
      context: ./nats
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data/nats

  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    ports:
      - "50051:50051"
      - "50052:50052"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_CLIENT_CERT=/app/nats/certs/client.crt
      - NATS_CLIENT_KEY=/app/nats/certs/client.key
      - NATS_ROOT_CA=/app/nats/certs/ca.crt
      - TRIGGER_INTERVAL=15s
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./master:/app/master
      - ./nats/certs:/app/nats/certs:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  nats_data: {}
