apiVersion: praetor.io/v1alpha1
kind: Catalog
metadata:
  name: default-catalog
spec:
  resources:
    - apiVersion: praetor.io/v1alpha1
      kind: File
      metadata:
        name: managed-by-master
      spec:
        path: /tmp/managed_by_master.txt
        content: "This file is managed by the MASTER (v4).\nHostname: {{ .facts.hostname }}\nOS: {{ .facts.os }}\nDB_PASSWORD: {{ secret \"default\" \"db-creds\" \"password\" }}"
        ensure: present
        mode: "0644"
    - apiVersion: praetor.io/v1alpha1
      kind: File
      metadata:
        name: to-be-deleted
      spec:
        path: /tmp/to_be_deleted.txt
        ensure: absent
    - apiVersion: praetor.io/v1alpha1
      kind: Package
      metadata:
        name: nginx
      spec:
        name: nginx
        ensure: present
    - apiVersion: praetor.io/v1alpha1
      kind: Service
      metadata:
        name: nginx
      spec:
        name: nginx
        ensure: running
        enable: true
    - apiVersion: praetor.io/v1alpha1
      kind: Exec
      metadata:
        name: write_hello
      spec:
        command: "echo 'Hello from Praetor Exec!' > /tmp/praetor_exec.log"
        creates: "/tmp/praetor_exec.log"
