package storage

import (
	"context"

	"github.com/guilledipa/praetor/proto/gen/master"
)

// Provider abstracts the persistent storage backend for Configuration Master state reports.
type Provider interface {
	// StoreReport persists a single resource execution trace generated by an Agent Node.
	StoreReport(ctx context.Context, nodeID string, report *master.ResourceReport) error

	// ListAgents returns a list of all active or historically registered agent node IDs.
	ListAgents(ctx context.Context) ([]string, error)

	// GetAgentReports returns all stored compliance reports for a single node ID.
	GetAgentReports(ctx context.Context, nodeID string) ([]*master.ResourceReport, error)

	// StoreAuditLog perpetually records an operator intervention.
	StoreAuditLog(ctx context.Context, action string, targetNode string, operatorID string) error
}
