package storage

import (
	"context"

	"github.com/guilledipa/praetor/proto/gen/master"
)

// Provider abstracts the persistent storage backend for Configuration Master state reports.
type Provider interface {
	// StoreReport persists a single resource execution trace generated by an Agent Node.
	StoreReport(ctx context.Context, nodeID string, report *master.ResourceReport) error
}
