name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Install dependencies and Tidy
      run: make tidy

    - name: Run golangci-lint (Agent)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        working-directory: agent

    - name: Run golangci-lint (Master)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        working-directory: master

    - name: Run golangci-lint (Pkg)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        working-directory: pkg

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Test globally across workspace
      run: make test

    - name: Build binaries
      run: make build
